### ISSUE TITLE
关于生成标签图

### ISSUE THREAD

**Issue by bbzqr** [xdFai/EDGSP#2]
想咨询一下您，如果我现在有一个数据集，只有图片和中心点标签，如果我只进行训练可以生成对应的mask图吗？

**Comment by bbzqr** [comment]
或者说我应该如何做，才能得到需要的mask图

**Comment by xdFai** [comment]
跑模型的推理文件，为每个一张需要打标签的图制备一个单点提示的掩码图。
其实我这个进一步做成软件就好了，就可以直接标注了




袁帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdFai/EDGSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 中午1:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [xdFai/EDGSP] 关于生成标签图 (Issue #2)





 
或者说我应该如何做，才能得到需要的mask图

**Comment by xdFai** [comment]
不训练&nbsp; 是直接用我给的权重进行推理&nbsp; 只跑推理就可以获取mask了




袁帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xdFai/EDGSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 中午1:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xdFai/EDGSP] 关于生成标签图 (Issue #2)





 
想咨询一下您，如果我现在有一个数据集，只有图片和中心点标签，如果我只进行训练可以生成对应的mask图吗？

**Comment by bbzqr** [comment]
感谢您的工作和讲解，我已经顺利实现了数据集的标注！

**Comment by xdFai** [comment]
好好 太棒啦&nbsp; 我也是比较忙叨&nbsp; 没有及时回复&nbsp; 能帮到你就好&nbsp; 祝一切顺利~&nbsp;


袁帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月30日(星期三) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xdFai/EDGSP] 关于生成标签图 (Issue #2)














 
感谢您的工作和讲解，我已经顺利实现了数据集的标注！

**Comment by lzh-google** [comment]
> 跑模型的推理文件，为每个一张需要打标签的图制备一个单点提示的掩码图。
> 其实我这个进一步做成软件就好了，就可以直接标注了
> 
> 
> 
> 
> 袁帅
> ***@***.***
> 
> 
> 
> &nbsp;
> […](#)
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "xdFai/EDGSP"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年10月29日(星期二) 中午1:03
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;Re: [xdFai/EDGSP] 关于生成标签图 (Issue [#2](https://github.com/xdFai/EDGSP/issues/2))
> 
> 
> 
> 
> 
> 
> 或者说我应该如何做，才能得到需要的mask图
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

必须生成一个对应的单点提示的掩码图吗，我尝试直接输入坐标，结果得到全黑的mask，可能是我的代码有问题？

**Comment by xdFai** [comment]
是的，代码里的处理流程必须需要将一个坐标生成一个提示掩码图，应该是您代码的问题。

这份工程的处理流程、网络模型和权重文件都是公开的，按照需求去修改就好。

**Comment by lzh-google** [comment]
> 感谢您的工作和讲解，我已经顺利实现了数据集的标注！

您好，能提供一下代码吗，本人能力不足属实没办法调通代码得到掩码。

**Comment by lzh-google** [comment]
> 是的，代码里的处理流程必须需要将一个坐标生成一个提示掩码图，应该是您代码的问题。
> 
> 这份工程的处理流程、网络模型和权重文件都是公开的，按照需求去修改就好。

谢谢您，不过我又试了试还是没得到掩码，我再尝试一下吧
