### ISSUE TITLE
关于可视化测试结果

### ISSUE THREAD

**Issue by watanabetoruc** [xdFai/EDGSP#4]
请问在未来会公开该工作的可视化测试结果代码吗？

**Comment by xdFai** [comment]
test文件里面，将save_img 设置成True 就可以可视化了

**Comment by watanabetoruc** [comment]
> test文件里面，将save_img 设置成True 就可以可视化了

感谢您的解答。可能是我表达的有误，我指的是使用者在红外小目标单点后生成标注这一过程的可视化代码，请问日后是否会公开？谢谢。

**Comment by watanabetoruc** [comment]
> test文件里面，将save_img 设置成True 就可以可视化了

感谢您的解答。可能是我表达的有误，我指的是使用者在红外小目标单点后生成标注这一过程的可视化代码，请问日后是否会公开？谢谢。

**Comment by xdFai** [comment]
我可能理解的不对 您说的这个过程是模型对数据标注的推理过程吗？
如果是的话 就是设置成True就可以了


或者说您的意思是一个真正交互的软件界面？ 这个我还没有做

&nbsp;


袁帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月19日(星期四) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xdFai/EDGSP] 关于可视化测试结果 (Issue #4)














  
test文件里面，将save_img 设置成True 就可以可视化了
  
感谢您的解答。可能是我表达的有误，我指的是使用者在红外小目标单点后生成标注这一过程的可视化代码，请问日后是否会公开？谢谢。
